--- 
clone: 
  depth: 1
kind: pipeline
name: DaffaPipeline
steps: 
  - 
    commands: 
      - "curl https://raw.githubusercontent.com/Daffa06/myscripts/master/MASTER.sh | bash"
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
    image: fadlyas/kernel_dockerfile:latest
    name: compile
    trigger: 
      branch: 
        - master